In [1]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns
import numpy as np # type: ignore
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)
transposed_array = array.T
print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[79 99 85]
 [91 47 65]
 [ 4  7 86]]

Transposed Array:
[[79 91  4]
 [99 47  7]
 [85 65 86]]


In [2]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array
import numpy as np

# Step 1: Generate a 1D array with 10 elements
array_1d = np.arange(10)
print("Original 1D Array:\n",array_1d)


# Step 2: Reshape the array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:")
print(array_2x5)

# Step 3: Reshape the array into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)
print("\nReshaped to 5x2 Array:")
print(array_5x2)


Original 1D Array:
 [0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
#  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array
import numpy as np

# Step 1: Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

# Step 2: Add a border of zeros around the array
array_6x6 = np.zeros((6, 6))
array_6x6[1:5, 1:5] = array_4x4
print(array_6x6)


Original 4x4 Array:
[[0.65416753 0.69729494 0.56551887 0.91488736]
 [0.47910938 0.40925168 0.32035425 0.32187263]
 [0.06270824 0.33529045 0.54570481 0.30562802]
 [0.05184603 0.4712748  0.39830648 0.3894426 ]]

6x6 Array with Zero Border (Manual Method):
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.65416753 0.69729494 0.56551887 0.91488736 0.        ]
 [0.         0.47910938 0.40925168 0.32035425 0.32187263 0.        ]
 [0.         0.06270824 0.33529045 0.54570481 0.30562802 0.        ]
 [0.         0.05184603 0.4712748  0.39830648 0.3894426  0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5
np.arange(10, 60, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [6]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations 
# (uppercase, lowercase, title case, etc.) to each element
l=['python', 'numpy', 'pandas']
arr = np.array(l)
print(np.char.upper(arr))
print(np.char.lower(arr))
print(np.char.capitalize(arr))

['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


In [10]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
words = np.asarray(['hello', 'world', 'numpy', 'array'])
spaced_words = np.array([' '.join(i) for i in words])
print("Original Array of Words:")
print(words)
print("\nArray of Words with Spaces Between Characters:")
print(spaced_words)


Original Array of Words:
['hello' 'world' 'numpy' 'array']

Array of Words with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


In [12]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[3 4 2]
 [3 3 3]
 [2 2 3]]
[[-1  0  0]
 [-1  1 -1]
 [ 0  0 -1]]
[[2 4 1]
 [2 2 2]
 [1 1 2]]
[[0.5 1.  1. ]
 [0.5 2.  0.5]
 [1.  1.  0.5]]


In [14]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements
# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)
diagonal_elements = np.diagonal(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [24]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)
print("Random Integers Array:")
print(random_integers)


def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True
prime_numbers = [num for num in random_integers if is_prime(num)]
print("\nPrime Numbers in the Array:")
print(prime_numbers)
print(len(prime_numbers))



Random Integers Array:
[419 890 549 844 362 120 443 595 958 822 726 101 717 573 583 626 463 557
 896 875 675  25 185 254  12 371 416 680 244 498 240 831 548 903 827 569
 125 661 582 369 791 206 168 225 488 901 266 431 268 975 658 588 226 968
 498 336 448 404 455 504 492  98 146 379 959 159 609 215 149 965 876 232
  35 410 447 607 173 730 598 622 888 524 438 372 700 192 778 764 109 460
 815 736 368  40 138 777 306 623 623 436]

Prime Numbers in the Array:
[np.int32(419), np.int32(443), np.int32(101), np.int32(463), np.int32(557), np.int32(827), np.int32(569), np.int32(661), np.int32(431), np.int32(379), np.int32(149), np.int32(607), np.int32(173), np.int32(109)]
14


In [33]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
# averages
# For example, temperatures can range from -10 to 35 degrees Celsius
daily_temperatures = np.random.randint(-10, 36, size=30)
print("Daily Temperatures for the Month:")
print(daily_temperatures)
weekly_averages = np.mean(daily_temperatures)
print("\nWeekly Average Temperatures:")
print(weekly_averages)


Daily Temperatures for the Month:
[ 10  15  22  -6  29   3  -8  -2  -5  30  27   5   0  -6  11  21  -1  16
  23   9  22  35  10   1  15  14  10 -10  35  -3]

Weekly Average Temperatures:
10.733333333333333
